---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paven-parent-pom
  annotations:
    backstage.io/techdocs-ref: dir:.
    google.com/cloudbuild-project-slug: paven-common-v3
    google.com/cloudbuild-location: us-west2
    #sonarqube.org/project-key: Round-Feather_paven-core-vehicles-service_AYZNUzTFmcNYwvVWpkVz

spec:
  type: library
  lifecycle: production
  owner: guests
